language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn test --coverage
  - yarn build-storybook
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
