language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn test --coverage
  - yarn build
  - yarn build-storybook
after_success:
  - yarn release
  - git remote show origin
  - git push https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG --follow-tags origin master    
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
