language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn test
deploy:
- provider: script
    script: yarn deploy
    on:
      branch: master