language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn test
  - yarn build-storybook
deploy:
  provider: script
  script: yarn deploy
  skip_cleanup: true
  on:
    branch: master
