language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn test --coverage
  - yarn build-storybook
  - yarn build
after_success:
  - yarn release
  - git push --follow-tags https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG.git master    
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    tags: true
