version: '3.8'

services:
 web:
  build:
   context: .
   target: dev
  ports:
   - 3000:3000
  environment:
   - CHOKIDAR_USEPOLLING=true
  volumes:
   - ./:/code
   - /code/node_modules
  command: yarn start
 storybook:
  build:
   context: .
   target: dev
  ports:
   - 9009:9009
  volumes:
   - ./:/code
   - /code/node_modules
  command: yarn storybook
